lb_port: 8005
strategy: round-robin
backends:
  - "http://localhost:8001"
  - "http://localhost:8002"
  - "http://localhost:8003"
  - "http://localhost:8004"
health_check_interval_in_sec: 30
max_retries: 5